name: Build and Publish
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # The cache is written to at the end of the build
    # If the build is successful
    - name: Cache htmlproofer and open-uri network calls
      uses: actions/cache@v3
      with:
        path: |
          _cache
          /tmp/.htmlproofer
        key: ${{ runner.os }}-network
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
      env:
        NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    - name: Build website
      run: ./_script/cibuild
    # Validating HTML with remote link validation
    # is always flaky, so we ignore if it fails
    - name: validate html
      run: bundle exec rake test
      continue-on-error: true
    # Deploy!
    - name: Publish to GitHub Pages
      run: ./_script/deploy.sh
      env:
        GH_REF: github.com/hackercouch/hackercouch.git
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.ref_name == 'master' }}
